# Generated by Django 5.2 on 2026-05-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0002_newsarticle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(default='', upload_to='articles/'),
            preserve_default=False,
        ),
    ]
