# Generated by Django 5.2 on 2026-05-19 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0004_newsarticle_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterModelOptions(
            name='newsportal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='portalcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='journalist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journalist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news_site.journalist'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
