# Generated by Django 5.2 on 2026-05-19 10:50

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Create Groups
    journalist_group, _ = Group.objects.get_or_create(name='Journalist')
    admin_group, _ = Group.objects.get_or_create(name='Admin')
    
    # Assign permissions to Journalist
    # Journalists can add/change/delete NewsArticle
    article_ct = ContentType.objects.get_for_model(apps.get_model('news_site', 'NewsArticle'))
    perms = Permission.objects.filter(content_type=article_ct)
    journalist_group.permissions.set(perms)


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0005_alter_advertisement_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
