# Generated by Django 5.2 on 2026-05-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0007_category_slug_journalist_slug_newsarticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalist',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
