from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('article/<slug:slug>/', views.article_detail, name='article_detail'),
    path('article/create/', views.article_create, name='article_create'),
    path('article/<slug:slug>/edit/', views.article_edit, name='article_edit'),
    path('article/<slug:slug>/delete/', views.article_delete, name='article_delete'),
    path('my-articles/', views.my_articles, name='my_articles'),
    path('category/<slug:slug>/', views.category_articles, name='category_articles'),
    path('journalist/<slug:slug>/', views.journalist_detail, name='journalist_detail'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('my-admin/', views.custom_admin_dashboard, name='custom_admin_dashboard'),
    path('my-admin/articles/', views.admin_articles, name='admin_articles'),
    path('my-admin/articles/<slug:slug>/delete/', views.admin_article_delete, name='admin_article_delete'),
    path('my-admin/users/', views.admin_users, name='admin_users'),
    path('my-admin/users/<int:pk>/toggle-staff/', views.admin_user_toggle_staff, name='admin_user_toggle_staff'),
    path('my-admin/comments/', views.admin_comments, name='admin_comments'),
    path('my-admin/comments/<int:pk>/delete/', views.admin_comment_delete, name='admin_comment_delete'),
    path('my-admin/categories/', views.admin_categories, name='admin_categories'),
    path('my-admin/categories/create/', views.admin_category_create, name='admin_category_create'),
    path('my-admin/categories/<slug:slug>/edit/', views.admin_category_edit, name='admin_category_edit'),
    path('my-admin/categories/<slug:slug>/delete/', views.admin_category_delete, name='admin_category_delete'),
    path('my-admin/subscriptions/', views.admin_subscriptions, name='admin_subscriptions'),
]